//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit
import Eureka

protocol ___VARIABLE_sceneName___ViewControllerInput {
    func displayForm(viewModel: ___VARIABLE_sceneName___Scene.GetForm.ViewModel)
}

protocol ___VARIABLE_sceneName___ViewControllerOutput {
    func getForm(request: ___VARIABLE_sceneName___Scene.GetForm.Request)
}

class ___VARIABLE_sceneName___ViewController: FormViewController, ___VARIABLE_sceneName___ViewControllerInput {
    
    var output: ___VARIABLE_sceneName___ViewControllerOutput?
    var router: ___VARIABLE_sceneName___Router?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        ___VARIABLE_sceneName___Configurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.getForm()
    }
    
    // MARK: Requests
    private func getForm() {
        let request = ___VARIABLE_sceneName___Scene.GetForm.Request()
        self.output?.getForm(request: request)
    }
    
    // MARK: Display logic
    func displayForm(viewModel: ___VARIABLE_sceneName___Scene.GetForm.ViewModel) {
        self.form = viewModel.form
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName___PresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
