//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import Eureka

protocol ___VARIABLE_sceneName___PresenterInput {
    func presentForm(response: ___VARIABLE_sceneName___Scene.GetForm.Response)
}

protocol ___VARIABLE_sceneName___PresenterOutput: class {
    func displayForm(viewModel: ___VARIABLE_sceneName___Scene.GetForm.ViewModel)
}

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresenterInput {
    
    weak var output: ___VARIABLE_sceneName___PresenterOutput?
    
    // MARK: Presentation logic
    func presentForm(response: ___VARIABLE_sceneName___Scene.GetForm.Response) {
        let form = Form()
        let viewModel = ___VARIABLE_sceneName___Scene.GetForm.ViewModel(form: self.form(response: response))
        self.output?.displayForm(viewModel: viewModel)
    }
    
    private func form(response: ___VARIABLE_sceneName___Scene.GetForm.Response) -> Form {
        let form = Form()
        +++ Section("Section 1")
        <<< LabelRow("Row 1")
        <<< LabelRow("Row 2")
        return form
    }
}
