//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ___VARIABLE_sceneName___InteractorInput {
    func getForm(request: ___VARIABLE_sceneName___Scene.GetForm.Request)
}

protocol ___VARIABLE_sceneName___InteractorOutput {
    func presentForm(response: ___VARIABLE_sceneName___Scene.GetForm.Response)
}

protocol ___VARIABLE_sceneName___DataSource {
    
}

protocol ___VARIABLE_sceneName___DataDestination {
    
}

class ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___InteractorInput, ___VARIABLE_sceneName___DataSource, ___VARIABLE_sceneName___DataDestination {
    
    var output: ___VARIABLE_sceneName___InteractorOutput?
    
    // MARK: Business logic
    func getForm(request: ___VARIABLE_sceneName___Scene.GetForm.Request) {
        let response = ___VARIABLE_sceneName___Scene.GetForm.Response()
        self.output?.presentForm(response: response)
    }

}
